export const events = [
  // Valid Events
  {
    id: "adsasagsdas",
    timestamp: "2023-01-01T00:00:00.000Z",
    payload: {
      targetEntity: "product",
      targetId: "123",
      action: "view",
      actionBG: "прегледа",
      userId: "123",
      userName: "Petar Stoyanov",
      userNameBG: "Петър Стоянов",
      source: "web",
      sourceBG: "уеб",
      productDetails: {
        category: "Dress",
        categoryBG: "Рокля",
        price: 49.99,
        stock: 20,
      },
      metadata: {
        browser: "Chrome",
        location: "Bulgaria",
        locationBG: "България",
      },
    },
  },
  {
    id: "adsasagsdab",
    timestamp: "2023-01-02T12:00:00.000Z",
    payload: {
      targetEntity: "product",
      targetId: "124",
      action: "purchase",
      actionBG: "закупи",
      userId: "124",
      userName: "Ivan Petrov",
      userNameBG: "Иван Петров",
      source: "mobile_app",
      sourceBG: "мобилно приложение",
      productDetails: {
        category: "Hat",
        categoryBG: "Шапка",
        price: 19.99,
        stock: 50,
        quantity: 2,
      },
      metadata: { os: "iOS", location: "Serbia", locationBG: "Сърбия" },
    },
  },
  {
    id: "adsasagsdae",
    timestamp: "2023-01-04T16:00:00.000Z",
    payload: {
      targetEntity: "product",
      targetId: "789",
      action: "add_to_cart",
      actionBG: "добави в количката",
      userId: "127",
      userName: "Maria Costa",
      userNameBG: "Мария Коста",
      source: "mobile_app",
      sourceBG: "мобилно приложение",
      productDetails: {
        category: "Pants",
        categoryBG: "Панталони",
        price: 39.99,
        stock: 10,
        quantity: 1,
      },
      metadata: { os: "Android", location: "Brazil", locationBG: "Бразилия" },
    },
  },
  {
    id: "adsasagsdaf",
    timestamp: "2023-01-04T17:00:00.000Z",
    payload: {
      targetEntity: "product",
      targetId: "790",
      action: "add_to_cart",
      actionBG: "добави в количката",
      userId: "128",
      userName: "Carlos Silva",
      userNameBG: "Карлос Силва",
      source: "web",
      sourceBG: "уеб",
      productDetails: {
        category: "Shoes",
        categoryBG: "Обувки",
        price: 79.99,
        stock: 5,
        quantity: 1,
      },
      metadata: {
        browser: "Edge",
        location: "Portugal",
        locationBG: "Португалия",
      },
    },
  },
  {
    id: "adsasagsdak",
    timestamp: "2023-01-09T22:00:00.000Z",
    payload: {
      targetEntity: "product",
      targetId: "3333",
      action: "view",
      actionBG: "прегледа",
      userId: "133",
      userName: "Eve Roberts",
      userNameBG: "Ева Робъртс",
      source: "mobile_app",
      sourceBG: "мобилно приложение",
      productDetails: {
        category: "Jacket",
        categoryBG: "Яке",
        price: 99.99,
        stock: 15,
      },
      metadata: { os: "iOS", location: "Spain", locationBG: "Испания" },
    },
  },
];
